name: Test

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  job:
    name: Test job
    runs-on: ubuntu-18.04

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Print variable
        run: |
          echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          echo "WORKFLOW_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo $WORKFLOW_URL

      - name: Bark notify
        if: always()
        uses: shink/bark-action@v1
        with:
          key: ${{ secrets.BARK_KEY }}
          title: Compilation work is over
          body: see ${{ env.WORKFLOW_URL }}
